### PR TITLE
Semifinal files for lean Project

### PR DESCRIPTION
**Pull request by Moldavarim**
we might do some last minute changes to the presentation based on timing

### CODE REVIEW

**Review by matematiflo — CHANGES_REQUESTED** [review]
Please do not include `lake-manifest.json` and the `lean-toolchain` file in your PR (you should do a `git pull` first, followed by `lake update` if you wish, to make sure that you are up-to-date with the current version of the repo (since you did not do it, you may need to revert the two files above manually, back to their original state). Please do so and then resubmit.

**Comment by Moldavarim** [comment]
Lean files are reverted into original state as requested

**Review by matematiflo — CHANGES_REQUESTED** [review]
Thanks, but there is still an issue with the `lean-toolchain` and `lake-manifest.json` files. You should update to the same version as the repo.

**Comment by Moldavarim** [comment]
> Thanks, but there is still an issue with the `lean-toolchain` and `lake-manifest.json` files. You should update to the same version as the repo.
Could you pealse explain further what the problem is with these files?
As far as i know, the contents of the 'lean-toolchain' and 'lake-manifest.json' files are exactly the same.

**Comment by matematiflo** [comment]
> > Thanks, but there is still an issue with the `lean-toolchain` and `lake-manifest.json` files. You should update to the same version as the repo.
> 
> Could you pealse explain further what the problem is with these files? As far as i know, the contents of the 'lean-toolchain' and 'lake-manifest.json' files are exactly the same.

Weird. There must be a subtle difference but I am not seeing it in the `git diff`. I suggest:

1. Reverting your changes on the `lean-toolchain` file.
2. Stashing your changes in the other file.
3. Do a `git pull` on the repo.
4. Unstash your files and commit them to the repo.

**Comment by matematiflo** [comment]
The `lean-toolchain` file should not be part of your pull request.

**Comment by Moldavarim** [comment]
I restored the lean-toolchain file to its original form. 
Hopfully should fix the problem

**Pull request merged**
