### PR TITLE
Add installation guide for Sage via conda-forge

### PR DESCRIPTION
**Pull request by Splines**
I've written a small installation/usage guide that might be helpful when seminar-participants want to 
- install SageMath via conda-forge
- and/or use Sage locally in Jupyter Notebooks inside VSCode.

See the preview of the new Readme [here](https://github.com/Splines/CompAssistedMath2024/tree/docs/installation-guide/Sage#installation-of-sage-via-conda-forge) (and [here](https://github.com/Splines/CompAssistedMath2024/tree/docs/installation-guide) for a possible new "root" Readme)

### CODE REVIEW

**Comment by matematiflo** [comment]
Looks good! Couple of requests before merging:

- Could you add to the README in the Sage folder, as opposed to the root of the CompAssistedMath2024 repo?
- In the command line, sometimes you use `condo`, sometimes you use `mamba`. Is there a reason?
- The one notebook in the Sage folder we have does work very well yet, when we open it in VS Code using this method: the `show(A)` command does not seem to produce the kind of [LaTeX display](https://matematiflo.github.io/SoSe_2024/code/01_Matrices.html) one might hope for. Is there a fix for that?

Finally, for easier use, it might be better to split 

```shell
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh
```

into 

```shell
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
```

and 

```shell
bash Miniforge3-$(uname)-$(uname -m).sh
```

Nice work!

**Comment by Splines** [comment]
> Could you add to the README in the Sage folder, as opposed to the root of the CompAssistedMath2024 repo?

Done

> In the command line, sometimes you use conda, sometimes you use mamba. Is there a reason?

No, there's no reason. I changed it to [`mamba`](https://mamba.readthedocs.io/en/latest/index.html), a faster drop-in replacement for `conda`.

> the show(A) command does not seem to produce the kind of LaTeX display one might hope for. Is there a fix for that?

I've added that to the "tips" sections. Click on the three `...` next to the cell, then "Change presentation". Unfortunately, I haven't found a VSCode setting yet to change this behavior for all Jupyter Notebooks.

**Review by matematiflo — APPROVED** [review]
Nice, thanks!

**Review by matematiflo — APPROVED** [review]
I really appreciate you making the effort to make this installation guide user-friendly. Having this kind of detailed exposition available will be a big help to people configuring their environment for the first time.

**Review by matematiflo — APPROVED** [review]

**Review by matematiflo — APPROVED** [review]
I wasn't too sure about the html at first, but since you've made a nice effort to write this, I'll incorporate the changes! Thanks for the work you've put into this 😊

**Pull request merged**
