### PR TITLE
Our hand in for the presentation

### PR DESCRIPTION
**Pull request by ComedyStudios**
Contains small change in the presentation and major changes for the lean file

### CODE REVIEW

**Review by matematiflo — CHANGES_REQUESTED** [review]
The file `Lagrange.lean` does not match our original file, does it? If this is indeed not the case, please provide the original file again and resubmit.

**Comment by ComedyStudios** [comment]
I have replaced the lagrange.lean file with the initial file, to make it clear our project is inside Simon-Mischa-Lagrange.lean

**Review by ComedyStudios — COMMENTED** [review]
replaced the Lagrange.lean with the inicial file

**Review by matematiflo — APPROVED** [review]
OK, merged!

**Pull request merged**
